eureka:
  client:
    service-url:
      defaultZone: http://eureka7002:7002/eureka
    register-with-eureka: false
    fetch-registry: false
  instance:
    instance-id: eureka7001
    prefer-ip-address: true
    hostname: eureka7001
spring:
  rabbitmq:
    host: 192.168.1.8
    port: 5672
    username: admin
    password: admin
